//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceProcessingLog
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> RecordsProcessed { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Status { get; set; }
        public string ErrorMessage { get; set; }
    }
}
