//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySettingMaster
    {
        public int SettingId { get; set; }
        public int CompanyId { get; set; }
        public int BusinessUnitId { get; set; }
        public int LEId { get; set; }
        public int LocationId { get; set; }
        public string Shift { get; set; }
        public System.TimeSpan ShiftStart { get; set; }
        public System.TimeSpan ShiftEnd { get; set; }
        public int MinWorkHoursDay { get; set; }
        public int MinWorkHoursWeek { get; set; }
        public int PayDay { get; set; }
        public int HalfDayLossHours { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> CompWrkHrs { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public string WeeklyHolidays { get; set; }
        public Nullable<int> WorkingHoursPerDay { get; set; }
        public Nullable<int> WeeklyWorkingHours { get; set; }
    }
}
