//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompOffRequest
    {
        public int CompOffReqId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpCode { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string ManagerCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Project { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string Task { get; set; }
        public string ActualHrs { get; set; }
        public Nullable<decimal> Hrs { get; set; }
        public string WorkMode { get; set; }
        public Nullable<bool> IsRequested { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    }
}
