//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAttendance
    {
        public int CId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Mobile { get; set; }
        public string Mail { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string Skill { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> ERPVendorId { get; set; }
        public string VendorCode { get; set; }
        public string Vendor { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ERPProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string Project { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string Site { get; set; }
        public string SiteDetails { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string ManagerEmpCode { get; set; }
        public string ManagerName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public Nullable<bool> IsLogout { get; set; }
        public Nullable<System.TimeSpan> LoginTime { get; set; }
        public Nullable<System.TimeSpan> LogoutTime { get; set; }
        public Nullable<System.TimeSpan> Activehrs { get; set; }
        public Nullable<System.TimeSpan> Approvedhrs { get; set; }
        public string LoginAddress { get; set; }
        public string LoginLonqitude { get; set; }
        public string LoginLatitude { get; set; }
        public string LogoutAddress { get; set; }
        public string LogoutLonqitude { get; set; }
        public string LogoutLatitude { get; set; }
        public Nullable<bool> IsLogoutManager { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Description { get; set; }
        public string ManPowerApproval { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
