//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttendanceRecord
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string DayName { get; set; }
        public Nullable<bool> IsWeekend { get; set; }
        public Nullable<bool> IsHoliday { get; set; }
        public string LogInTime { get; set; }
        public string LogOutTime { get; set; }
        public string ESSLLogInTime { get; set; }
        public string ESSLLogOutTime { get; set; }
        public string WFHLogInTime { get; set; }
        public string WFHLogOutTime { get; set; }
        public string ONSITELogInTime { get; set; }
        public string ONSITELogOutTime { get; set; }
        public string WorkingHours { get; set; }
        public Nullable<decimal> WorkingHoursDecimal { get; set; }
        public Nullable<int> CompId { get; set; }
        public string CompName { get; set; }
        public string Designation { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<decimal> DailyPay { get; set; }
        public string LeaveType { get; set; }
        public string WorkType { get; set; }
        public Nullable<int> DaysPresent { get; set; }
        public Nullable<decimal> PayDays { get; set; }
        public string ActiveHours { get; set; }
        public string ESSLActiveHours { get; set; }
        public string WFHActiveHours { get; set; }
        public string ONSITEActiveHours { get; set; }
        public string MANUALActiveHours { get; set; }
        public string ShiftName { get; set; }
        public string BreakTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
