//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_Offc_ConEntities : DbContext
    {
        public DB_Offc_ConEntities()
            : base("name=DB_Offc_ConEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessPolicy> AccessPolicies { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<AttendanceProcessingLog> AttendanceProcessingLogs { get; set; }
        public virtual DbSet<BannerMaster> BannerMasters { get; set; }
        public virtual DbSet<BusinessUnitMaster> BusinessUnitMasters { get; set; }
        public virtual DbSet<CareerMaster> CareerMasters { get; set; }
        public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<CompanySettingMaster> CompanySettingMasters { get; set; }
        public virtual DbSet<CompOffRequest> CompOffRequests { get; set; }
        public virtual DbSet<ConfigMaster> ConfigMasters { get; set; }
        public virtual DbSet<ConfigSetup> ConfigSetups { get; set; }
        public virtual DbSet<ContractAttendance> ContractAttendances { get; set; }
        public virtual DbSet<CPwdManagement> CPwdManagements { get; set; }
        public virtual DbSet<DailyAttendanceRecord> DailyAttendanceRecords { get; set; }
        public virtual DbSet<DeptMaster> DeptMasters { get; set; }
        public virtual DbSet<DesignationMaster> DesignationMasters { get; set; }
        public virtual DbSet<DocumentMaster> DocumentMasters { get; set; }
        public virtual DbSet<EducationMaster> EducationMasters { get; set; }
        public virtual DbSet<EmailConfigMaster> EmailConfigMasters { get; set; }
        public virtual DbSet<EmailSetUp> EmailSetUps { get; set; }
        public virtual DbSet<Emp_AttendanceTime> Emp_AttendanceTime { get; set; }
        public virtual DbSet<EmpEmailTrackingLog> EmpEmailTrackingLogs { get; set; }
        public virtual DbSet<EmpLeaveApplication> EmpLeaveApplications { get; set; }
        public virtual DbSet<EmployeeAccDetail> EmployeeAccDetails { get; set; }
        public virtual DbSet<EmployeeCareer> EmployeeCareers { get; set; }
        public virtual DbSet<EmployeeCareerDetail> EmployeeCareerDetails { get; set; }
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<EmployeeDoc> EmployeeDocs { get; set; }
        public virtual DbSet<EmployeeEducation> EmployeeEducations { get; set; }
        public virtual DbSet<EmployeeGovtDoc> EmployeeGovtDocs { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<EmployeeMaster0312> EmployeeMaster0312 { get; set; }
        public virtual DbSet<EmployeeMaster1> EmployeeMaster1 { get; set; }
        public virtual DbSet<EmployeeMaster2> EmployeeMaster2 { get; set; }
        public virtual DbSet<EmployeeMasterLog> EmployeeMasterLogs { get; set; }
        public virtual DbSet<EmployeeMasterNew> EmployeeMasterNews { get; set; }
        public virtual DbSet<EmployeeNomineeMaster> EmployeeNomineeMasters { get; set; }
        public virtual DbSet<EmployeeSalaryDetail> EmployeeSalaryDetails { get; set; }
        public virtual DbSet<EmpProbationTrackingHistory> EmpProbationTrackingHistories { get; set; }
        public virtual DbSet<EmpShiftDetail> EmpShiftDetails { get; set; }
        public virtual DbSet<EmpTypeMaster> EmpTypeMasters { get; set; }
        public virtual DbSet<FinanceMaster> FinanceMasters { get; set; }
        public virtual DbSet<FinancialYearMaster> FinancialYearMasters { get; set; }
        public virtual DbSet<FPwdManagement> FPwdManagements { get; set; }
        public virtual DbSet<GenderMaster> GenderMasters { get; set; }
        public virtual DbSet<GradeMaster> GradeMasters { get; set; }
        public virtual DbSet<HolidayMaster> HolidayMasters { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<LeaveCarryForwardMaster> LeaveCarryForwardMasters { get; set; }
        public virtual DbSet<LeaveTypeMaster> LeaveTypeMasters { get; set; }
        public virtual DbSet<LegalEntityMaster> LegalEntityMasters { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<Loginlog> Loginlogs { get; set; }
        public virtual DbSet<ManualAttendance> ManualAttendances { get; set; }
        public virtual DbSet<ModuleMaster> ModuleMasters { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationTemplate> NotificationTemplates { get; set; }
        public virtual DbSet<OnSiteLoginlog> OnSiteLoginlogs { get; set; }
        public virtual DbSet<PageModuleMaster> PageModuleMasters { get; set; }
        public virtual DbSet<PassHistoryManagement> PassHistoryManagements { get; set; }
        public virtual DbSet<PayoutMappingMaster> PayoutMappingMasters { get; set; }
        public virtual DbSet<PayrollComponent> PayrollComponents { get; set; }
        public virtual DbSet<PayrollComponentCondition> PayrollComponentConditions { get; set; }
        public virtual DbSet<PayrollComponentLogic> PayrollComponentLogics { get; set; }
        public virtual DbSet<PayrollFrequencyMaster> PayrollFrequencyMasters { get; set; }
        public virtual DbSet<PayrollPayoutType> PayrollPayoutTypes { get; set; }
        public virtual DbSet<PayrollSegment> PayrollSegments { get; set; }
        public virtual DbSet<PayrollSymbolMaster> PayrollSymbolMasters { get; set; }
        public virtual DbSet<PayrollVariable> PayrollVariables { get; set; }
        public virtual DbSet<PayslipSection> PayslipSections { get; set; }
        public virtual DbSet<PayslipSectionComponent> PayslipSectionComponents { get; set; }
        public virtual DbSet<Per_BehaviourDetail> Per_BehaviourDetail { get; set; }
        public virtual DbSet<Per_BehaviourMaster> Per_BehaviourMaster { get; set; }
        public virtual DbSet<Per_Goal> Per_Goal { get; set; }
        public virtual DbSet<Per_SelfDevelopment> Per_SelfDevelopment { get; set; }
        public virtual DbSet<Per_Task> Per_Task { get; set; }
        public virtual DbSet<ProjectConnectUser> ProjectConnectUsers { get; set; }
        public virtual DbSet<ProjectMaster> ProjectMasters { get; set; }
        public virtual DbSet<QuaterMaster> QuaterMasters { get; set; }
        public virtual DbSet<ReviewList> ReviewLists { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<SalutationMaster> SalutationMasters { get; set; }
        public virtual DbSet<ServiceMaster> ServiceMasters { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProviders { get; set; }
        public virtual DbSet<SessionMaster> SessionMasters { get; set; }
        public virtual DbSet<ShiftGroupingMaster> ShiftGroupingMasters { get; set; }
        public virtual DbSet<ShiftMaster> ShiftMasters { get; set; }
        public virtual DbSet<SiteMaster> SiteMasters { get; set; }
        public virtual DbSet<SubModuleMaster> SubModuleMasters { get; set; }
        public virtual DbSet<TempManualAttendance> TempManualAttendances { get; set; }
        public virtual DbSet<UserNotification> UserNotifications { get; set; }
        public virtual DbSet<VariableHistory> VariableHistories { get; set; }
        public virtual DbSet<VendorMaster> VendorMasters { get; set; }
        public virtual DbSet<VisitorInviteHistory> VisitorInviteHistories { get; set; }
        public virtual DbSet<VisitorManagement> VisitorManagements { get; set; }
        public virtual DbSet<WeekHoliday> WeekHolidays { get; set; }
        public virtual DbSet<WFHLoginlog> WFHLoginlogs { get; set; }
        public virtual DbSet<WorkTypeMaster> WorkTypeMasters { get; set; }
    
        public virtual int sp_InsertAttendanceData(Nullable<System.DateTime> startDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertAttendanceData", startDateParameter);
        }
    
        public virtual int sp_InsertAttendanceData1(Nullable<System.DateTime> startDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertAttendanceData1", startDateParameter);
        }
    
        public virtual ObjectResult<GetAttendanceExceptions_Result> GetAttendanceExceptions(Nullable<int> loginId)
        {
            var loginIdParameter = loginId.HasValue ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAttendanceExceptions_Result>("GetAttendanceExceptions", loginIdParameter);
        }
    
        public virtual int InsertValidAttendance(Nullable<int> loginId)
        {
            var loginIdParameter = loginId.HasValue ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertValidAttendance", loginIdParameter);
        }
    
        public virtual int sp_GetAttendanceReport(Nullable<int> loginId, Nullable<int> compId, Nullable<int> lEId, Nullable<int> bUId, Nullable<int> locId, Nullable<int> deptId, Nullable<int> designationId, Nullable<int> empId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var loginIdParameter = loginId.HasValue ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(int));
    
            var compIdParameter = compId.HasValue ?
                new ObjectParameter("CompId", compId) :
                new ObjectParameter("CompId", typeof(int));
    
            var lEIdParameter = lEId.HasValue ?
                new ObjectParameter("LEId", lEId) :
                new ObjectParameter("LEId", typeof(int));
    
            var bUIdParameter = bUId.HasValue ?
                new ObjectParameter("BUId", bUId) :
                new ObjectParameter("BUId", typeof(int));
    
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("DeptId", deptId) :
                new ObjectParameter("DeptId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetAttendanceReport", loginIdParameter, compIdParameter, lEIdParameter, bUIdParameter, locIdParameter, deptIdParameter, designationIdParameter, empIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int sp_GetDepartmentDailyAttendanceReport(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> compId, Nullable<int> lEId, Nullable<int> bUId, Nullable<int> locId, Nullable<int> deptId)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var compIdParameter = compId.HasValue ?
                new ObjectParameter("CompId", compId) :
                new ObjectParameter("CompId", typeof(int));
    
            var lEIdParameter = lEId.HasValue ?
                new ObjectParameter("LEId", lEId) :
                new ObjectParameter("LEId", typeof(int));
    
            var bUIdParameter = bUId.HasValue ?
                new ObjectParameter("BUId", bUId) :
                new ObjectParameter("BUId", typeof(int));
    
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("DeptId", deptId) :
                new ObjectParameter("DeptId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetDepartmentDailyAttendanceReport", startDateParameter, endDateParameter, compIdParameter, lEIdParameter, bUIdParameter, locIdParameter, deptIdParameter);
        }
    
        public virtual int sp_ProcessLeaveCredits(Nullable<System.DateTime> currentDate)
        {
            var currentDateParameter = currentDate.HasValue ?
                new ObjectParameter("CurrentDate", currentDate) :
                new ObjectParameter("CurrentDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessLeaveCredits", currentDateParameter);
        }
    
        public virtual int sp_ProcessDailyAttendanceRecords(Nullable<System.DateTime> processDate)
        {
            var processDateParameter = processDate.HasValue ?
                new ObjectParameter("ProcessDate", processDate) :
                new ObjectParameter("ProcessDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessDailyAttendanceRecords", processDateParameter);
        }
    
        public virtual int sp_InsertAttendanceDataManual(Nullable<System.DateTime> startDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertAttendanceDataManual", startDateParameter);
        }
    
        public virtual int sp_GetReporteesAttendanceReport(Nullable<int> loginId, Nullable<int> compId, Nullable<int> lEId, Nullable<int> bUId, Nullable<int> locId, Nullable<int> deptId, Nullable<int> designationId, Nullable<int> empId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var loginIdParameter = loginId.HasValue ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(int));
    
            var compIdParameter = compId.HasValue ?
                new ObjectParameter("CompId", compId) :
                new ObjectParameter("CompId", typeof(int));
    
            var lEIdParameter = lEId.HasValue ?
                new ObjectParameter("LEId", lEId) :
                new ObjectParameter("LEId", typeof(int));
    
            var bUIdParameter = bUId.HasValue ?
                new ObjectParameter("BUId", bUId) :
                new ObjectParameter("BUId", typeof(int));
    
            var locIdParameter = locId.HasValue ?
                new ObjectParameter("LocId", locId) :
                new ObjectParameter("LocId", typeof(int));
    
            var deptIdParameter = deptId.HasValue ?
                new ObjectParameter("DeptId", deptId) :
                new ObjectParameter("DeptId", typeof(int));
    
            var designationIdParameter = designationId.HasValue ?
                new ObjectParameter("DesignationId", designationId) :
                new ObjectParameter("DesignationId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetReporteesAttendanceReport", loginIdParameter, compIdParameter, lEIdParameter, bUIdParameter, locIdParameter, deptIdParameter, designationIdParameter, empIdParameter, startDateParameter, endDateParameter);
        }
    }
}
