//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_AttendanceTime
    {
        public int EmpAttendance { get; set; }
        public Nullable<int> LogId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public Nullable<int> AttendHours { get; set; }
        public Nullable<int> AttendMins { get; set; }
        public Nullable<int> AttendSec { get; set; }
        public string SalType { get; set; }
        public string EmpCode { get; set; }
    }
}
