//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpEmailTrackingLog
    {
        public int LogId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmailType { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> ProbationEndDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
