//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string AMobileNo { get; set; }
        public string PMailId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string HusbandName { get; set; }
        public string FContactNo { get; set; }
        public string MContactNo { get; set; }
        public string HContactNo { get; set; }
        public string EContactNo { get; set; }
        public string EContactName { get; set; }
        public string EContactRelationship { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<System.DateTime> DateOfAnniversary { get; set; }
        public string Disability { get; set; }
        public string ECActivities { get; set; }
        public string Sports { get; set; }
        public string Caste { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string Nationality { get; set; }
        public string TotalExperience { get; set; }
        public string RelevantExperience { get; set; }
        public string PermanentDoorNumber { get; set; }
        public string PermanentBuildingName { get; set; }
        public string PermanentStreet { get; set; }
        public string PermanentLocation { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentState { get; set; }
        public string PermanentCountry { get; set; }
        public string PermanentPinCode { get; set; }
        public string CurrentDoorNumber { get; set; }
        public string CurrentBuildingName { get; set; }
        public string CurrentStreet { get; set; }
        public string CurrentLocation { get; set; }
        public string CurrentCity { get; set; }
        public string CurrentState { get; set; }
        public string CurrentCountry { get; set; }
        public string CurrentPinCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string EContactNo1 { get; set; }
        public string EContactName1 { get; set; }
        public string EContactRelationship1 { get; set; }
        public string EContactNo2 { get; set; }
        public string EContactName2 { get; set; }
        public string EContactRelationship2 { get; set; }
    }
}
