//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCareerDetail
    {
        public int CareerId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Experience { get; set; }
        public string PMonth1 { get; set; }
        public string PaySlip1 { get; set; }
        public string PMonth2 { get; set; }
        public string PaySlip2 { get; set; }
        public string PMonth3 { get; set; }
        public string PaySlip3 { get; set; }
        public string OfferLetter { get; set; }
        public string SalaryLetter { get; set; }
        public string ExperienceLetter { get; set; }
        public string RelievingLetter { get; set; }
        public string ContactName { get; set; }
        public string ContactDesignation { get; set; }
        public string ContactEmail { get; set; }
        public string ContactMobile { get; set; }
        public string CTC { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
