//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeGovtDoc
    {
        public int GovId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<int> DocId { get; set; }
        public string DocName { get; set; }
        public string Others { get; set; }
        public string Name { get; set; }
        public string DocNo { get; set; }
        public string IssuedDate { get; set; }
        public string ExpiredDate { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
