//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryDetail
    {
        public int SalaryId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpCode { get; set; }
        public Nullable<decimal> CTC { get; set; }
        public Nullable<decimal> MCTC { get; set; }
        public Nullable<decimal> PerviousCTC { get; set; }
        public Nullable<decimal> IncrementPercent { get; set; }
        public Nullable<System.DateTime> EffectiveFromDate { get; set; }
        public Nullable<System.DateTime> EffectiveToDate { get; set; }
        public Nullable<bool> IsAppraised { get; set; }
        public Nullable<bool> RecordStatus { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public Nullable<bool> IsVariable { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> VariableId { get; set; }
        public string VariableName { get; set; }
        public string VariableCode { get; set; }
        public string VariableAmt { get; set; }
        public Nullable<bool> IsArrear { get; set; }
        public string ArrearAmt { get; set; }
        public Nullable<bool> IsClearArrear { get; set; }
        public Nullable<int> PendingMonth { get; set; }
        public Nullable<int> ArrearYear { get; set; }
        public Nullable<int> ArrearMonth { get; set; }
        public string DescriptionforArrear { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
