//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpProbationTrackingHistory
    {
        public int EmpProbationId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> ProbationDays { get; set; }
        public Nullable<System.DateTime> ProbationEndDate { get; set; }
        public Nullable<int> ReportId { get; set; }
        public string ReportCode { get; set; }
        public Nullable<bool> IsProbation { get; set; }
        public Nullable<bool> IsPermanent { get; set; }
        public Nullable<bool> IsContract { get; set; }
        public Nullable<bool> IsConsultant { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<int> ConfirmBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastupdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
