//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Holiday_Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int Created_By { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<int> Modify_By { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string HolidayType { get; set; }
        public string Location { get; set; }
    }
}
