//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCarryForwardMaster
    {
        public int CFId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpCode { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<int> LeaveYear { get; set; }
        public Nullable<int> LeaveMonth { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> Availed { get; set; }
        public Nullable<decimal> CarryForward { get; set; }
        public Nullable<decimal> Encashment { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
