//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveTypeMaster
    {
        public int LeaveTypeId { get; set; }
        public string LocationId { get; set; }
        public string YearType { get; set; }
        public string LeaveName { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string DurationType { get; set; }
        public string ApplicableTo { get; set; }
        public string EmpTypeId { get; set; }
        public string EmpLevel { get; set; }
        public Nullable<bool> CarryForward { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<bool> IsMonth { get; set; }
        public Nullable<bool> IsYear { get; set; }
        public Nullable<int> MaxCarryForward { get; set; }
        public Nullable<bool> Encashable { get; set; }
        public Nullable<int> MaxApply { get; set; }
        public Nullable<int> MaxPerMonth { get; set; }
        public Nullable<int> MaxPerYear { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> ApplicableDuration { get; set; }
        public Nullable<bool> IsSingleApplication { get; set; }
        public Nullable<int> MaxAllowedEvents { get; set; }
        public Nullable<bool> WeekEndInclusive { get; set; }
        public Nullable<bool> ResetYear { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
