//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMaster
    {
        public int LocationId { get; set; }
        public Nullable<int> CompId { get; set; }
        public Nullable<int> LEId { get; set; }
        public Nullable<int> BUId { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string LocationMap { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string TimeZone { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public string WeeklyHoliday { get; set; }
        public string CompanyRegNo { get; set; }
        public string DateofReg { get; set; }
        public string PFNo { get; set; }
        public string ESINo { get; set; }
        public string TANNo { get; set; }
        public string VATNo { get; set; }
        public string PANNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public string GSTNo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
