//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTemplate
    {
        public int TemplateId { get; set; }
        public string TemplateName { get; set; }
        public string NotificationType { get; set; }
        public string NotificationSubType { get; set; }
        public string TitleTemplate { get; set; }
        public string MessageTemplate { get; set; }
        public string TargetRoles { get; set; }
        public string DefaultIcon { get; set; }
        public string DefaultColor { get; set; }
        public string ActionUrlTemplate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
