//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notification()
        {
            this.UserNotifications = new HashSet<UserNotification>();
        }
    
        public int NotificationId { get; set; }
        public Nullable<System.Guid> NotificationGuid { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string ShortDescription { get; set; }
        public string NotificationType { get; set; }
        public string NotificationSubType { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<System.Guid> ReferenceGuid { get; set; }
        public string ActionUrl { get; set; }
        public string ActionText { get; set; }
        public string NotificationIcon { get; set; }
        public string NotificationColor { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotification> UserNotifications { get; set; }
    }
}
