//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnSiteLoginlog
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpCode { get; set; }
        public string Company { get; set; }
        public string LoginAddress { get; set; }
        public string LoginCity { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public string LoginLongitude { get; set; }
        public string LoginLatitude { get; set; }
        public Nullable<System.TimeSpan> LogInTime { get; set; }
        public string LogoutAddress { get; set; }
        public string LogoutCity { get; set; }
        public string Purpose { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LogoutDate { get; set; }
        public string LogoutLongitude { get; set; }
        public string LogoutLatitude { get; set; }
        public Nullable<System.TimeSpan> LogOutTime { get; set; }
        public Nullable<System.TimeSpan> ActiveHrs { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
