//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollSymbolMaster
    {
        public int SymbolId { get; set; }
        public string Symbol { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
