//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollComponentLogic
    {
        public int LogicId { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> SNo { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> ComponentId1 { get; set; }
        public string ComponentName1 { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PayrollComponent PayrollComponent { get; set; }
    }
}
