//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Per_SelfDevelopment
    {
        public int Id { get; set; }
        public Nullable<int> QId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public string Activity { get; set; }
        public string ActionDescription { get; set; }
        public string ActionType { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string EDescription { get; set; }
        public string MDescription { get; set; }
        public Nullable<bool> ReviewedByEmp { get; set; }
        public Nullable<bool> ReviewedByManager { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
