//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Per_Goal
    {
        public int GoalId { get; set; }
        public Nullable<int> QId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string Goal { get; set; }
        public string Description { get; set; }
        public string Weightage { get; set; }
        public string EmpReview { get; set; }
        public string ManagerReview { get; set; }
        public string EDescription { get; set; }
        public string MDescription { get; set; }
        public string Status { get; set; }
        public Nullable<bool> FinalSubmit { get; set; }
        public Nullable<bool> ReviewedByEmp { get; set; }
        public Nullable<bool> ReviewedByManager { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
