//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMaster
    {
        public int ProjectId { get; set; }
        public Nullable<int> ERPProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string Project { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProjectManagerId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string Site { get; set; }
        public string ManagerCode { get; set; }
        public string ManagerName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
