//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewList
    {
        public int ReviewId { get; set; }
        public Nullable<int> FYearId { get; set; }
        public Nullable<int> QId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string QType { get; set; }
        public string Status { get; set; }
        public Nullable<bool> ReviewedByEmp { get; set; }
        public Nullable<bool> ReviewedByManager { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
