//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string Error { get; set; }
        public string Archieve { get; set; }
        public string Output { get; set; }
    }
}
