//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionMaster
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string TockenId { get; set; }
        public string AuthKey { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<bool> WFH { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
