//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int UserNotificationId { get; set; }
        public int NotificationId { get; set; }
        public int UserId { get; set; }
        public string UserRole { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<bool> IsStarred { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<bool> IsActionTaken { get; set; }
        public Nullable<System.DateTime> ActionTakenDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Notification Notification { get; set; }
    }
}
