//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorManagement
    {
        public int VisitId { get; set; }
        public string RegNo { get; set; }
        public string QR { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Company { get; set; }
        public string Purpose { get; set; }
        public string PMail { get; set; }
        public string OMail { get; set; }
        public string Mobile { get; set; }
        public string AMobile { get; set; }
        public string Photo { get; set; }
        public string CompId { get; set; }
        public Nullable<int> WhomtoMeet { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public Nullable<bool> Invited { get; set; }
        public Nullable<bool> Accept { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> Expired { get; set; }
        public string Accessories { get; set; }
        public Nullable<bool> DirectCheckIn { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public string IdCard { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
