//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeConnect_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTypeMaster
    {
        public int WorkTypeId { get; set; }
        public string WorkType { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Reason { get; set; }
        public string ApproverDescription { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> IsApprovedBy { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<int> IsRejectedBy { get; set; }
        public Nullable<bool> IsEnd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastupdatedDate { get; set; }
    }
}
